# ===============================================================
# pyproject.toml (The Great Synthesis)
# ===============================================================

[project]
name = "permission_test"
version = "1.0.0"
dependencies = [
    # We use a modern Flet version that supports the handler
    "flet==0.28.3",
    "flet_cli==0.28.3",
    "flet-permission-handler",
]

# ===============================================================
# Flet-specific build settings
# ===============================================================

[tool.flet]
product_name = "Permission Test"

[tool.flet.build]
build_number = 1
build_version = "1.0.0"

[tool.flet.build.apk]
package_name = "com.hekma.permissiontest"

[tool.flet.android.permission]
"android.permission.READ_EXTERNAL_STORAGE" = true
"android.permission.WRITE_EXTERNAL_STORAGE" = true
[tool.serious_python]
no_pep517 = true
# ===============================================================
# The Two Critical Fixes Together
# ===============================================================

# Fix #1: Solves the Dart language version error
[tool.flet.flutter.pubspec.dependency_overrides]
webview_flutter_android = "4.10.1"