# ===============================================================
# pyproject.toml (The Final Source of Truth v2)
# ===============================================================

[project]
# [الإصلاح]: استخدام اسم صالح بدون مسافات
name = "permission_test"
version = "1.0.0"
dependencies = [
    "flet==0.28.0",
    "flet-permission-handler"
]

# ===============================================================
# Flet-specific build settings
# ===============================================================

[tool.flet]
# هذا هو المكان الصحيح لتعريف product_name حسب توثيق flet
product_name = "Permission Test"

[tool.flet.build]
build_number = 1
build_version = "1.0.0"

[tool.flet.build.apk]
# project_name و package_name هنا لم يعد لهما لزوم لأن flet سيقرأهم من [project]
package_name = "com.hekma.permissiontest"

[tool.flet.build.apk.android.permission]
"android.permission.READ_EXTERNAL_STORAGE" = true
"android.permission.WRITE_EXTERNAL_STORAGE" = true