# pyproject.toml


[tool.flet.build]
build_number = 1
build_version = "1.0.0"

[tool.flet.build.apk]
project_name = "Permission Test"
package_name = "com.hekma.permissiontest"

[tool.flet.build.apk.requirements]
"flet-permission-handler" = { path = "vendor/flet-permission-handler" }

[tool.flet.build.apk.android.permission]
"android.permission.READ_STORAGE" = true
"android.permission.WRITE_STORAGE" = true

# The fix for the build error
[tool.flet.flutter.pubspec.dependency_overrides]
webview_flutter_android = "4.10.1"