name: Surgical Build Test (Windows) 3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Install Dependencies from pyproject.toml
      run: pip install .

    # [الإصلاح]: استخدام الطريقة الصحيحة والمضمونة لقبول التراخيص في PowerShell
    - name: Accept Android Licenses Surgically
      run: |
        $sdkmanager = Join-Path $env:ANDROID_HOME "cmdline-tools/latest/bin/sdkmanager.bat"
        echo $("y`n" * 20) | & $sdkmanager --licenses
      shell: pwsh

    - name: Verify Environment
      run: flutter doctor -v
      shell: pwsh

    - name: Build APK
      run: flet build apk --verbose
      shell: pwsh

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-win-surgical.apk
        path: build\apk\app-release.apk