name: Build Flet Android APK (Linux)

on:
  workflow_dispatch: # هنخليه يدوي فقط عشان نتحكم فيه

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Set up Java (Required on Linux)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Flet and Dependencies
      run: pip install flet

    - name: Build APK
      run: flet build apk --verbose

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-linux.apk
        path: build/apk/app-release.apk