name: Surgical Build Test (Windows) 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    # [الإصلاح 1]: استخدام Java 21 لتتوافق مع Flutter الحديث
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    # استخدام أحدث إصدار من Flutter
    - name: Set up Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Install Dependencies from pyproject.toml
      run: pip install .

    # [الإصلاح 2]: استخدام sdkmanager مباشرة لقبول التراخيص
    - name: Accept Android Licenses Surgically
      run: echo $("y`n" * 10) | ${env:ANDROID_HOME}\cmdline-tools\latest\bin\sdkmanager.bat --licenses

    - name: Verify Environment
      run: flutter doctor -v

    - name: Build APK
      run: flet build apk --verbose

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-win-surgical.apk
        path: build\apk\app-release.apk