name: Build Flet Android APK (Linux)

on:
  workflow_dispatch:

env:
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1
  FLUTTER_VERSION: "3.19.6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # [الإصلاح]: إعادة خطوة تثبيت Flutter الصريحة
    - name: Set up Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true

    - name: Install Flet
      run: pip install flet
      
    - name: Accept Android Licenses
      run: yes | flutter doctor --android-licenses --suppress-analytics

    - name: Build APK
      run: flet build apk --verbose

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-linux.apk
        path: build/apk/app-release.apk