name: Flutter

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'Operating system'
        required: true
        default: 'ubuntu-latest'
        type: string
      channel:
        description: 'Flutter channel'
        required: true
        default: 'stable'
        type: string
      version:
        description: 'Flutter version'
        required: true
        default: 'latest'
        type: string

jobs:
  flutter:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          channel: ${{ inputs.channel }}
          version: ${{ inputs.version }}

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses
      - name: Dart version
        run: dart --version
      - name: Flutter version
        run: flutter --version
      - name: Flutter doctor
        run: flutter doctor

      - name: Install flet-cli
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli==$FLET_CLI_VERSION

      - name: Build APK
        run: |
          flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION \
          --android-permissions android.permission.READ_CONTACTS=True \
          android.permission.WRITE_CONTACTS=True

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/apk/
      